---
# packages
# https://linux-ha.osdn.jp/wp/dl
pm_extra_tools_url: https://osdn.net/frs/redir.php?m=dotsrc&f=linux-ha%2F74514%2Fpm_extra_tools-1.2-1.el8.noarch.rpm

postgresql_url: https://download.postgresql.org/pub/repos/yum/13/redhat/rhel-8-x86_64/
postgresql_packages:
  - postgresql13-libs-13.3-2PGDG.rhel8.x86_64.rpm
  - postgresql13-13.3-2PGDG.rhel8.x86_64.rpm
  - postgresql13-server-13.3-2PGDG.rhel8.x86_64.rpm
  - postgresql13-contrib-13.3-2PGDG.rhel8.x86_64.rpm
  - postgresql13-docs-13.3-2PGDG.rhel8.x86_64.rpm

pg_rex_operation_url: https://osdn.net/frs/redir.php?m=xtom_us&f=pg-rex%2F74642%2Fpg-rex13-1.0-1.tar.gz

# user configure
root_password: root

# pacemaker configure
pcmk_user: hacluster
pcmk_password: hacluster
pcm_resource_conf_dir: /root

# postgresql configure
postgresql_PGDATA: /dbfp/pgdata/data
postgresql_bin: /usr/pgsql-13/bin
postgresql_data:
  { path: "/dbfp/pgdata/data", owner: "postgres", group: "postgres", mode: "700" }
postgresql_wal:
  { path: "/dbfp/pgwal/pg_wal", owner: "postgres", group: "postgres", mode: "700" }
postgresql_archive:
  { path: "/dbfp/pgarch/arc1", owner: "postgres", group: "postgres", mode: "700" }
postgresql_settings:
  - listen_addresses = '*'
  - password_encryption = scram-sha-256
  - wal_level = replica
  - synchronous_commit = on
  - archive_mode = always
  - archive_command = '/bin/cp %p /dbfp/pgarch/arc1/%f'
  - max_wal_senders = 10
  - wal_keep_size = 512MB
  - wal_sender_timeout = 20s
  - max_replication_slots = 10
  - hot_standby = on
  - max_standby_archive_delay = -1
  - max_standby_streaming_delay = -1
  - hot_standby_feedback = on
  - wal_receiver_timeout = 20s
  - restart_after_crash = off
postgresql_service: postgresql-13
postgresql_repuser: { name: "repuser", password: "reppasswd" } 

# network
slan:
  - { host: "pgrex01", nic: "eth1", ip: "192.168.1.10" , cidr: 24 }
  - { host: "pgrex02", nic: "eth1", ip: "192.168.1.20" , cidr: 24 }
  - { host: "ping"   , nic: "eth1", ip: "192.168.1.1"  , cidr: 24}

dlan:
  - { host: "pgrex01", nic: "eth2", ip: "192.168.2.10", cidr: 24 }
  - { host: "pgrex02", nic: "eth2", ip: "192.168.2.20", cidr: 24 }

iclan:
  - { host: "pgrex01", nic: "eth3", ip: "192.168.3.10", cidr: 24 }
  - { host: "pgrex01", nic: "eth4", ip: "192.168.4.10", cidr: 24 }
  - { host: "pgrex02", nic: "eth3", ip: "192.168.3.20", cidr: 24 }
  - { host: "pgrex02", nic: "eth4", ip: "192.168.4.20", cidr: 24 }

stonithlan:  # stonith is not supported.
  - { host: "pgrex01", nic: "eth5", ip: "172.20.5.10", cidr: 24 }
  - { host: "pgrex02", nic: "eth5", ip: "172.20.5.20", cidr: 24 }

svlan:
  - { host: "primary",   nic: "eth1", ip: "192.168.1.11", cidr: 24 }
  - { host: "secondary", nic: "eth1", ip: "192.168.1.21", cidr: 24 }

dvlan:
  - { host: "replication", nic: "eth2", ip: "192.168.2.30", cidr: 24 }