---
- set_fact:
    pmc_resource: PG-REX_pm_pcsgen_env.csv

- name: distribute pacemaker resource configuration
  template:
    src: "root/{{ pmc_resource }}.j2"
    dest: "{{ pcm_resource_conf_dir }}/{{ pmc_resource }}"

- name: generate pacemaker resource xml file
  shell: sh -c "/bin/pm_pcsgen \"{{ pcm_resource_conf_dir }}/{{ pmc_resource }}\""
  args:
    chdir: "{{ pcm_resource_conf_dir }}"
